services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: BOT_TOKEN
        sync: false  # ito ay manual mong ilalagay sa dashboard
      - key: CARGO_HOME
        value: /tmp/.cargo
      - key: RUSTUP_HOME
        value: /tmp/.rustup
